 @startuml
digraph fsm {
    rankdir=LR;

    node [shape = point] start;
    node [shape = circle] s0
    node [shape = circle]; s1;
    node [shape = circle ]; s2;
    node [shape = circle] s3;
    
    node [shape = circle] s5;
    node [shape = circle] s6;
    
    node [shape = circle] s8;
    node [shape = circle] s9;
    node [shape = circle] s10;

    node [shape = circle] s12;
    node [shape = circle] s13;
    node [shape = circle] s14;
    node [shape = circle] s15;

    node [shape = doublecircle] end;

    start -> s0

    s0 -> s1 [label = "c"];

    s1 -> s2 [label = "a" ];
    
    s1 -> s5 [label = "h" ];
    s1 -> s8 [label = "o"];
    
    s2 -> s3 [label = "s"];
    s3 -> end [label = "e"];

    s5 -> s6 [label = "a"];
    s6 -> end [label = "r"];

    s8 -> s9 [label = "n"];
    
    s9 -> s10 [label = "s"];
    s9 -> s12 [label = "t"];

    s10 -> end [label = "t"];

    s12 -> s13 [label = "i"];
    s13 -> s14 [label = "n"];
    s14 -> s15 [label = "u"];
    s15 -> end [label = "e"];





}
@enduml